PROGRAM TRAP1
  IMPLICIT NONE
  DOUBLE PRECISION, PARAMETER :: PI = 3.14159265358979323846D0
  DOUBLE PRECISION :: INTEGRAL
  INTEGER :: N, K

  INTERFACE
     FUNCTION TRAPEZ(F, A, B, N)
       IMPLICIT NONE
       DOUBLE PRECISION, INTENT (in) :: A, B
       INTEGER, INTENT (in) :: N
       DOUBLE PRECISION :: TRAPEZ

       INTERFACE
          FUNCTION f(X)
            IMPLICIT NONE
            DOUBLE PRECISION, INTENT (in) ::  X
            DOUBLE PRECISION :: f
          END FUNCTION F
       END INTERFACE
     END FUNCTION TRAPEZ

     FUNCTION G(X)
       IMPLICIT NONE
       DOUBLE PRECISION, INTENT (in) ::  X
       DOUBLE PRECISION :: G
     END FUNCTION G
  END INTERFACE

  DO K = 1, 9
     N = 2**K
     INTEGRAL = TRAPEZ(G, 0.0D0, PI, N)
     PRINT *, N, INTEGRAL, 2.0D0-INTEGRAL
  ENDDO

END PROGRAM TRAP1

FUNCTION G(X)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT (in) ::  X
  DOUBLE PRECISION :: G
  G = SIN(X)
END FUNCTION G


FUNCTION TRAPEZ(F, A, B, N)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT (in) :: A, B
  INTEGER, INTENT (in) :: N
  DOUBLE PRECISION :: TRAPEZ

  INTERFACE
     FUNCTION f(X)
       IMPLICIT NONE
       DOUBLE PRECISION, INTENT (in) ::  X
       DOUBLE PRECISION :: f
     END FUNCTION F
  END INTERFACE

  INTEGER :: I
  DOUBLE PRECISION :: X, SUM, H

  H = (B-A) / N

  SUM = 0.5D0 * (F(A) + F(B)) 

  DO I= 1,N-1
     X = A + I * H

     SUM = SUM + F(X)
  ENDDO

  TRAPEZ = SUM * H
END FUNCTION TRAPEZ
